packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  unconfig: ^7.3.3
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsdown: ^0.14.2
    typescript: ^5.8.2
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
